#!/usr/bin/env bash
#
# One-shot local dev bootstrap. Idempotent — safe to re-run.
#
#   ./scripts/dev-bootstrap.sh
#
# What it does:
#   1. Verifies prerequisites (pnpm, supabase CLI, openssl, node).
#   2. Starts `supabase start` if not already running.
#   3. Applies every migration under supabase/migrations/.
#   4. Generates the command-signing keypair if you don't have one.
#   5. Writes apps/dashboard/.env.local with every required var
#      (only if the file doesn't already exist — won't clobber).
#   6. Runs scripts/seed-dev.sql to populate demo devices + commands.
#   7. Prints next steps.
#
# Non-goals: does NOT start the Next dev server (run that yourself
# in a separate tab so you can see its logs).

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

c_green() { printf '\033[32m%s\033[0m\n' "$*"; }
c_yellow() { printf '\033[33m%s\033[0m\n' "$*"; }
c_red() { printf '\033[31m%s\033[0m\n' "$*"; }
step() { printf '\n\033[1;34m==> %s\033[0m\n' "$*"; }

# --- 1. Prerequisites ------------------------------------------------

step "Checking prerequisites"
missing=()
for bin in pnpm supabase openssl node; do
    if ! command -v "$bin" >/dev/null 2>&1; then
        missing+=("$bin")
    fi
done
if [ ${#missing[@]} -gt 0 ]; then
    c_red "Missing required tools: ${missing[*]}"
    cat <<EOF

Install them:
  - pnpm:     npm install -g pnpm@10
  - supabase: brew install supabase/tap/supabase
  - openssl:  (should already be on macOS/Linux)
  - node:     nvm install 22 && nvm use 22

EOF
    exit 1
fi
c_green "OK: $(pnpm --version) / $(supabase --version) / $(openssl version | awk '{print $1" "$2}') / $(node --version)"

# --- 2. Install workspace deps (idempotent) --------------------------

step "Installing workspace deps"
pnpm install

step "Building @archiveglp/schema (type-check dep for dashboard)"
pnpm --filter @archiveglp/schema build

# --- 3. Start Supabase if not running --------------------------------

step "Starting Supabase (local)"
if supabase status 2>/dev/null | grep -q 'API URL'; then
    c_yellow "Supabase already running — skipping start"
else
    supabase start
fi

# Read credentials straight from `supabase status`.
SB_STATUS="$(supabase status)"
SB_API_URL="$(echo "$SB_STATUS" | awk -F': *' '/^\s*API URL/ {print $2; exit}')"
SB_ANON="$(echo   "$SB_STATUS" | awk -F': *' '/^\s*anon key/ {print $2; exit}')"
SB_SERVICE="$(echo "$SB_STATUS" | awk -F': *' '/^\s*service_role key/ {print $2; exit}')"
SB_DB_URL="$(echo "$SB_STATUS" | awk -F': *' '/^\s*DB URL/ {print $2; exit}')"

if [ -z "$SB_API_URL" ] || [ -z "$SB_ANON" ] || [ -z "$SB_SERVICE" ] || [ -z "$SB_DB_URL" ]; then
    c_red "Could not parse supabase status output. Try \`supabase status\` by hand."
    exit 1
fi
c_green "API URL: $SB_API_URL"

# --- 4. Apply migrations ---------------------------------------------

step "Applying migrations"
# supabase db reset would wipe data too. We just push everything forward.
for f in "$ROOT"/supabase/migrations/*.sql; do
    echo "  - $(basename "$f")"
    psql "$SB_DB_URL" -v ON_ERROR_STOP=1 -q -f "$f"
done

# --- 5. Ensure command-signing key exists ----------------------------

step "Command-signing keypair"
KEY_DIR="$ROOT/.dev-secrets"
KEY_DER="$KEY_DIR/command-signing.pkcs8.der"
mkdir -p "$KEY_DIR"
if [ ! -f "$KEY_DER" ]; then
    openssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:P-256 \
        -outform DER -out "$KEY_DER"
    c_green "Generated $KEY_DER"
else
    c_yellow "Reusing existing $KEY_DER"
fi
CMD_SIGN_B64="$(base64 -w0 "$KEY_DER" 2>/dev/null || base64 -b0 "$KEY_DER")"

# --- 6. Write .env.local if missing ----------------------------------

ENV_FILE="$ROOT/apps/dashboard/.env.local"
if [ -f "$ENV_FILE" ]; then
    c_yellow "$ENV_FILE already exists — not overwriting. Verify it contains:"
    cat <<EOF

  NEXT_PUBLIC_SUPABASE_URL=$SB_API_URL
  NEXT_PUBLIC_SUPABASE_ANON_KEY=$SB_ANON
  SUPABASE_SERVICE_ROLE_KEY=$SB_SERVICE
  FIRM_ID=firm_archdev001
  COMMAND_SIGNING_KEY_ID=local-1
  COMMAND_SIGNING_PRIVATE_KEY_B64=<base64 of .dev-secrets/command-signing.pkcs8.der>
  SUPERVISOR_STEPUP_PASSWORD=<anything>
  SESSION_SECRET=<32+ chars>
  ADMIN_API_KEY=<16+ chars>

EOF
else
    step "Writing $ENV_FILE"
    SESS_SECRET="$(openssl rand -base64 48 | tr -d '\n')"
    ADMIN_KEY="$(openssl rand -base64 36 | tr -d '\n')"
    cat > "$ENV_FILE" <<EOF
# Generated by scripts/dev-bootstrap.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# This file is gitignored. Delete + re-run the bootstrap to rotate.

NEXT_PUBLIC_SUPABASE_URL=$SB_API_URL
NEXT_PUBLIC_SUPABASE_ANON_KEY=$SB_ANON
SUPABASE_SERVICE_ROLE_KEY=$SB_SERVICE

FIRM_ID=firm_archdev001
ADMIN_API_KEY=$ADMIN_KEY
SESSION_SECRET=$SESS_SECRET

COMMAND_SIGNING_KEY_ID=local-1
COMMAND_SIGNING_PRIVATE_KEY_B64=$CMD_SIGN_B64

SUPERVISOR_STEPUP_PASSWORD=stepup-local
EOF
    c_green "Wrote $ENV_FILE"
fi

# --- 7. Seed demo data -----------------------------------------------

step "Seeding demo data (firm + 6 devices + commands + audit rows)"
psql "$SB_DB_URL" -v ON_ERROR_STOP=1 -q -f "$ROOT/scripts/seed-dev.sql"

# --- 8. Done ----------------------------------------------------------

cat <<EOF

$(c_green '✓ Bootstrap complete')

Next steps:
  1. Start the dev server (in another tab so you can watch its logs):
       pnpm --filter @archiveglp/dashboard dev
     → http://localhost:3001

  2. Open http://localhost:3001/login, enter any email (e.g.
     you@example.com), click Sign in. MVP mock auth: no password.

  3. Visit http://localhost:3001/devices — you should see six demo
     devices with health states: healthy, warning, silent, critical,
     paused, revoked. Click any row to drill in.

  4. On a device page:
       - "Diagnose" on dev_seed_silent returns the stored sample result
       - "Pause" prompts no step-up (not destructive)
       - "Revoke" / "Restart machine" prompt for the step-up password:
           SUPERVISOR_STEPUP_PASSWORD=stepup-local
         (or whatever you set in .env.local)
       - A queued pending_command on dev_seed_critical can be Canceled

  5. /audit is the new audit-log page.

  6. When you're done, stop Supabase with:  supabase stop

Gotcha: seeded devices carry dummy public keys and cannot actually
authenticate. They're for UI exercise only. To see real heartbeats /
ingest, enroll a real macOS agent per apps/agent/MAC_MINI_SETUP.md
(Mac-only).

EOF
